
import Header from '../components/Header'
import Navigation from '../components/Nav'
import Project from '../components/Project'
import Footer from '../components/Footer'
import styles from '../styles/styles.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Amanda M. Nelson</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles['body']}>

      <Navigation></Navigation>
      
      <Footer></Footer>
      </main>
      </>
  )
}
